In [1]:
import numpy as np

In [10]:
l = [3,1,3,4,5]
l

[3, 1, 3, 4, 5]

In [9]:
l2 = []
# hängt Elemente hinten an
l2.append(3)
l2.append(4)
l2

[3, 4]

In [11]:
# diese methode summiert l2
sum(l)

16

In [13]:
l

[1, 3, 3, 4, 5]

In [15]:
type(l)

list

In [22]:
# 1 dimensionales array
M_1D = np.array([1,2,3])

In [21]:
M_1D.shape

(3,)

In [26]:
M_2D = np.array([[1,2,3], [3,4,5],[6,7,8]])

M_2D

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
M_2D.shape

(3, 3)

In [69]:
naka_mat = np.array([[1,2,3],
                     [3,4,5],
                     [6,7,8],
                     [9,10,11]])


In [70]:
naka_mat

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [91]:
naka_mat[1,2] == 5

True

In [92]:
naka_mat

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
naka_mat.shape

(4, 3)

In [40]:
# indexierung der 1. Dimension
naka_mat[3,2]

11

In [41]:
naka_mat[2,1] == 7

True

In [42]:
naka_mat[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [ ]:
M_2D_[]

In [16]:
type(M)

numpy.ndarray

In [48]:
M_3D = np.array([[[1,2],[4,5]],
                 [[1,2],[4,5]]])

In [86]:
np.max(np.random.randn(100000000))

5.72180227524106

In [81]:
M_5D = np.random.rand(1,2,3)
M_5D

array([[[0.78863666, 0.39574457, 0.6636351 ],
        [0.16638317, 0.02720542, 0.84011382]]])

In [56]:
M_5D.shape

(13, 2, 3, 4, 5)

In [60]:
M_5D

array([], shape=(0, 2, 3, 4, 5), dtype=float64)

In [58]:
M_5D[11,0, 1, 2, 1]

0.6118978987880566

In [52]:
M_5D[0,0, 1, 2, 1]

0.12691567109695723

In [88]:
?np.random.uniform

In [ ]:
import numpy as np

# 1. Lineare Algebra

Lineare Algebra ist ein fundamentaler Baustein von Machine Learning.
Daher sind die Grundlagen und die Implementierung einiger Methoden interessant und wichtig.

Eine Matrix $M_{ij}$ (Zeile $i$ und Spalte $j$) können wir in Python mit einem 2 dimensionalem NumPy array sehr leicht darstellen.
Zum Beispiel folgende Telefonmatrix:

In [93]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ein Vektor hingegenen, wird oft als 1 dimensionales NumPy array ausgedrückt:

In [94]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

Versuche nun das richtige Ergebnis per Hand auszurechnen. Du kannst es dann mit folgendem Befehl überprüfen:

In [96]:
np.array([[1,2,3],
          [1,2,3],
          [1,2,3]]) * np.array([1, -1, 1],
                               [1, -1, 1],
                               [1,-1, 1])

array([[ 1, -2,  3],
       [ 1, -2,  3],
       [ 1, -2,  3]])

In [95]:
M * v

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [98]:
# trage auf der rechten Seite das richtige Ergebnis ein
np.all(np.dot(M, v) == np.array([14, 32, 50]))

True

In [99]:
# trage auf der rechten Seite das richtige Ergebnis ein
np.all(np.dot(M, np.array([3,2,1])) == np.array([10, 28, 46]))

True

Man kann von einer Matrix auch das transponierte Bilden: $M'$

Was bedeutet das? Finde die Antwort mit `np.transpose`

In [101]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
N = np.array([[1,2,3,4],
              [5,6,7,8]])

In [106]:
np.transpose(N)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [108]:
N.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [102]:
np.transpose(M)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [114]:
# trage auf der rechten Seite das richtige Ergebnis ein
np.dot(np.transpose(M), np.array([-1,1,-0.5])) == np.array([-0.5, -1.0, -1.5])

array([ True,  True,  True])

Man kann nicht nur eine Matrix mit einem Vektor multiplizieren, sondern auch eine Matrix mit einer Matrix.
Berechne das Ergebnis der folgenden Operation:

In [ ]:
np.all(np.dot(M, M) == np.array([[0,0,0], [0,0,0], [0,0,0]]))

In [ ]:
np.all(np.dot(M, -M) == np.array([[0,0,0], [0,0,0], [0,0,0]]))

In [ ]:
np.all(np.dot(-M, -M) == np.array([[0,0,0], [0,0,0], [0,0,0]]))

In [ ]:
M1 = np.array([[-1, 1], [1, -1]])
M2 = np.array([[2, -2], [3, -1]])

np.all(np.dot(M1, M2) == np.array([[0,0,0], [0,0,0], [0,0,0]]))
np.all(np.dot(M2, M1) == np.array([[0,0,0], [0,0,0], [0,0,0]]))

# 2. Matrix-Vektor Multiplikation selbst gemacht

Wir haben nun verstanden wie man Matrix-Vektor Multiplikationen in NumPy berechnet.
Nun möchten wir einen einfachen (und langsamen) Algorithmus per Hand schreiben.

Überprüfe das Ergebnis

In [117]:
np.zeros(3)

array([0., 0., 0.])

In [124]:
def mat_vec_mult(M, v):
    # Vektor mit Länge 3 mit 0er
    out = np.zeros(3)
    
    for zeile in range(3):
        #out[zeile] = M11 * v1 + M12 * v2 + M13 * v3
        out[zeile] = M[zeile,0] * v[0] + M[zeile,1] * v[1] + M[zeile,2] * v[2]   
                     #M21 * v1 * M22 * v2 + M23 * v3
            
    return out

In [134]:
def mat_vec_mult2(M, v):
    # Vektor mit Länge 3 mit 0er
    out = np.zeros(M.shape[0])
    
    for zeile in range(M.shape[0]):
        #for spalte in range(len(v)):
        for spalte in range(M.shape[1]):
            out[zeile] = out[zeile] + M[zeile,spalte] * v[spalte]
            
    return out

In [137]:
len(mat_vec_mult2(np.random.rand(99, 133), np.random.rand(133)))

99

In [146]:
# anzahl der Spalten
M.shape[1]

3

In [143]:
# anzahl der Zeilen
M.shape[0]

3

In [145]:
M.shape

(3, 3)

In [133]:
mat_vec_mult2(M, v)

array([14., 32., 50.])

In [123]:
mat_vec_mult(M, v)

array([14., 32., 50.])

In [121]:
np.matmul(M, v)

array([14, 32, 50])

Teste nun mit 10 zufälligen Matrizen und Vektoren, dass der Algorithmus stimmt.
Benutze dafür `np.random.rand` und `np.equal` und eine for schleife 

Anscheinend sind die Algorithmen nicht ganz gleich?
Woran liegt das?

Benutze statt `np.equal` `np.isclose`. Lies gerne die Dokumentation was diese Funktion macht.

In [ ]:
?np.equal

# 3. Matrix-Matrix Multiplikation

Schreibe einen Algorithmus, der Matrizen mit Matrizen multipliziert.

In [ ]:
def mat_mat_mult(A, B):
    
    return 0

Definiere zwei passende Matrizen `A` und `B`.

In [ ]:
mat_mat_mult(A, B)

In [ ]:
np.matmul(A, B)

In [ ]:
%timeit mat_mat_mult(A, B)

In [ ]:
%timeit np.matmul(A, B)

Verbesserung von Linearen Algebra Operationen hat eine sehr lange Geschichte.

Zum Vergleich sieht man, dass unsere naive Implementierung sehr langsam ist. 

Das liegt einerseits an Python selbst, da NumPy effektiv Fortran Routinen aufruft, die deutlich schneller und effizienter sind.
Python ist eine sehr langsame Sprache, da sie interpretiert und nicht kompiliert ist.

Andererseits optimiert Fortran sehr stark für verschiedene CPU Architekturen und versucht Zugriffe auf Arbeitsspeicher und z.B. Cache Misses zu minimieren.

# 4. Mehr Matrixspaß

In [ ]:
L1 = np.array([[0, -1],[1, 0]])

L2 = np.array([[0, 1],[-1, 0]])

In [ ]:
# korrigiere die rechte Seite
np.all(np.dot(L1, L2) == np.array([[0,0], [0,0]]))

In [ ]:
# korrigiere die rechte Seite
np.all(np.dot(L1, np.transpose(L1)) == np.array([[0,0],[0,0]]))

In [ ]:
# korrigiere die rechte Seite
np.all(np.dot(L2, np.transpose(L2)) == np.array([[0,0],[0,0]]))

# 5. Rotationsmatrizen

Mache dich mit dem Konzept von Rotationsmatrizen bekannt: https://de.wikipedia.org/wiki/Drehmatrix

Du musst natürlich nicht alles lesen, sondern nur verstehen wie man diese berechnet.

Definiere nun eine Funktion, mit der man Rotationsmatrizen für beliebige Winkel berechnet.
Multipliziere diese zu verschiedenen Vektoren und visualisiere diese.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
def rotations_matrix(angle):
    return 0

In [ ]:
rotations_matrix(0)

In [ ]:
rotations_matrix(np.pi/2)

In [ ]:
rotations_matrix(3*np.pi/2)

In [ ]:
rotations_matrix(np.pi)

In [ ]:
rotations_matrix(np.pi * 2)

Zeige nun folgende Identitäten zuerst progammatisch, danach analytisch!

Wieso gilt das? Was ist die qualitative Begründung? Wie ist die mathematische?

`np.dot(rotations_matrix(alpha), rotations_matrix(beta)) = rotations_matrix(alpha + beta)`

Versuche nun mit `matplotlib` und den Funktionen `plt.axes` und `ax.arrow` Vektoren zu plotten.
Damit kannst du das Theorem von oben ebenfalls visualisieren.

In [ ]:
v1 = np.array([1, 0])

In [ ]:
def plot_vectors(vectors):
    return
    

In [ ]:
plot_vectors([v1, np.dot(rotations_matrix(np.pi/2), v1)])